name: sublime_log
description: Flutter package which manages the logs message, view or share to other.
version: 1.0.1
homepage: https://github.com/tusaamf/sublime_log

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

environment:
  sdk: ">=3.0.1 <4.0.0"